default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: <%= ENV['DB_ENV_MYSQL_ROOT_PASSWORD'] %>
  host: <%= ENV['DB_PORT_3306_TCP_ADDR'] %>

development:
  <<: *default
  database: searchapp_development

test:
  <<: *default
  database: searchapp_test
  host: <%= ENV['DB_PORT_3306_TCP_ADDR'] %>

production:
  adapter: mysql2
  encoding: utf8
  database: <%= ENV['DB_ENV_MYSQL_NAME'] %>
  username: <%= ENV['DB_ENV_MYSQL_USER'] %>
  password: <%= ENV['DB_ENV_MYSQL_PASSWORD'] %>
  host: <%= ENV['DB_PORT_80_TCP_ADDR'] %>
  port: 80
